### ISSUE TITLE
As a backend developer I want to address major security concerns abouth the exposed API Key and Email keys.

### ISSUE THREAD

**Issue by Joshua-T-Winterflood** [sopra-fs24-group-39/MapMystery-Server#106]
# Acceptance Criteria
The system should store the API Keys and the Email tokens in an encrypted format and should only be decrypted on demand to access the Google API / Email Verification.

# Development Tasks:
- [x] #107
  - **Task**:  Create a secure way to store and encrypt the API Key and implement a function which decryptes the Key on runtime.
  - **Estimate**: 5h

- [x] #108
  - **Task**:  Create a safe way of dealing with the email tokens such that the email tokens are either discared when no longer needed ( Verification is done ) or are stored in an encrypted format to prevent third parties from Identity theft.
  - **Estimate**: 5h

Time estimate: 10h

**Comment by wallacees12** [comment]
Decide that this task was unnecessary and overly complex.
